package de.aittr.car_rent.domain.entity;

public enum CarTransmissionType {

    MANUAL,
    AUTOMATIC,
    SEMI_AUTOMATIC,
    DUAL_CLUTCH,
    TIPTRONIC,
    DIRECT_SHIFT_GEARBOX,
    TORQUE_CONVERTER,
    AUTOMATED_MANUAL_TRANSMISSION,
    CONTINUOUSLY_VARIABLE_TRANSMISSION
}
